### ISSUE TITLE
Issue when setting up a FileHandler in python

### ISSUE THREAD

**Issue by diego-jd** [lextudio/httpbridge#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is weird and somehow an issue, but when you declare any file handler (FileHandler, RotatingFileHandler, etc.) I get a HTTP Error 502.5 - HttpPlatformHandler Startup Failure.

The error doesn't show up when you use a StreamHandler

I declare the logger like this:

```
file_handler = logging.FileHandler(log_file)
file_handler.setLevel(logging.INFO)
file_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s - [in %(filename)s:%(lineno)d]')
file_handler.setFormatter(file_formatter)
```

and this is my web.config:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" requireAccess="Script" />
        </handlers>
        <httpPlatform stdoutLogEnabled="true" stdoutLogFile=".\python.log" startupTimeLimit="20" processPath="...\python.exe" arguments="-m waitress --port %HTTP_PLATFORM_PORT% wsgi:application">
        </httpPlatform>
    </system.webServer>
</configuration>
```

I tried changing stdoutLogEnabled to false but that didn't fixed it.

When I comment the logging.FileHandler() line, it works.

Any ideas what could it be?

### Expected Behavior

Being able to create log files from python without a HttpPlatformHandler error

### Steps To Reproduce

1. Create a simple flask app
2. Configure a file logger in it
3. Configure IIS
4. Open webpage
5. Error should arise

### Anything else?

I'm using VS Code, Windows Server 2019, IIS 10

**Comment by lextm** [comment]
By the default the application pool identity has no write permission on the web content folder (or other folders where you want to the log files to appear). Thus, using a file logger in your Python code can cause your Python process to exit due to unhandled errors.

I believe that's why HttpPlatformHandler detected and reported such an error. If so, changing the necessary NTFS permissions can resolve it. You might also use a tool like Process Monitor to analyze further.
